- id: last-modified
  name: Last Modified Hook
  description: Make a description here
  entry: last-modified-hook
  language: python
  types: [python]
  args: ["--seconds", "--line-limit", "--line-template"]
